### PR TITLE
Fix/update Windows CI

### PR DESCRIPTION
**Pull request by cmb69**
This should fix the build artifact upload which is broken as of 10e43f1eaf8c698a0758d428a4d19e1f17b0df2f (sorry, my bad). It should also use the caches of this repository to speed up the setup of the PHP SDK.

### CODE REVIEW

**Comment by cmb69** [comment]
@realFlowControl, it seems one (or more) of the test cases are flaky on Windows. I had to cancel PHP 8.2 after 30mins, and the previous run cancelled almost all Windows runners. I have no idea why; maybe an issue with the rather old pthreads 3.0.0? (unfortunately, there have been no releases for a couple of years)

**Comment by realFlowControl** [comment]
I have seen this as well, that sometimes one of the Windows tests is just super slow. Restarting it mostly works ...

**Review by realFlowControl — APPROVED** [review]

**Comment by realFlowControl** [comment]
Is there anything further I need to do for the artefacts to show up in pecl?

**Comment by cmb69** [comment]
The artifacts for PECL are built and uploaded by the https://github.com/php/php-windows-builder team. I guess they're just busy, and will upload soon.

The CI artifacts are just meant for testing purposes. E.g. checking that a bug fix works as expected.

**Comment by realFlowControl** [comment]
Thanks for the clarification 🙇

**Pull request merged**
