### PR TITLE
add support for pthreads4w v3

### PR DESCRIPTION
**Pull request by dktapps**
https://sourceforge.net/projects/pthreads4w/

### CODE REVIEW

**Comment by krakjoe** [comment]
Is there strong motivation for this ?

**Comment by dktapps** [comment]
Not really, it's just a nice-to-have.

**Comment by krakjoe** [comment]
I'm nervous to add this, we've been testing the Red Hat library for many many years ... also I can't even see this build on appveyor because the deps are not present ...

If you don't have strong motivation, and I'm nervous, we probably shouldn't do it ...

**Comment by dktapps** [comment]
FWIW I've been building pthreads against this for the last several months with no issues. There's also a 2.11.0 version which is binary compatible with 2.9.1.

pthreads4w = pthread-w32, just rebranded.

**Pull request closed without merging**
