### PR TITLE
PHP 8.1 support

### PR DESCRIPTION
**Pull request by flavioheleno**
This PR picks up from where #226 left - all the work was done by @dixyes - I just don't want to see this work wasted.

I may as well open a `PHP 8.2 support` branch from this and fix whatever I can.

### CODE REVIEW

**Comment by flavioheleno** [comment]
Interesting, the changes I did to fix the tests on Linux broke them on Windows..

**Comment by cmb69** [comment]
I think before going ahead with this, we should setup a working Linux CI (the existing Travis CI should be replaced).

Also, could you please rebase onto HEAD of the "develop" branch?

**Comment by flavioheleno** [comment]
@cmb69 I'll start another PR with GHA-based Linux CI; rebased as requested :-)

**Comment by flavioheleno** [comment]
Quick update so that you know this is still active, I'm working my way up into https://github.com/shivammathur/setup-php to have PHP 8.1/8.2 ZTS available in GitHub Actions so that I can setup Linux CI :-)

**Comment by krakjoe** [comment]
@cmb69 and I have added some CI for all target versions ... this gives us a better idea of how this is looking ...

unfortunately there are some failures and I haven't got to the reasons yet ...

When I have more free time, I'll come back to it, but feel free to investigate ...

**Comment by krakjoe** [comment]
@flavioheleno @cmb69 @dixyes thanks for the hard work :)

**Pull request merged**
