### PR TITLE
Added Channel::closed()

### PR DESCRIPTION
**Pull request by flavioheleno**
This is a shot at adding `Channel::closed()`, closing #136 :-)

### CODE REVIEW

**Comment by flavioheleno** [comment]
The build is failing for 7.2 series due to a syntax error on `run-tests.php`, for which I proposed a fix in here https://github.com/php/php-src/pull/5444.

**Comment by flavioheleno** [comment]
The build should be working now as https://github.com/php/php-src/pull/5444 got merged.

**Comment by flavioheleno** [comment]
ping @krakjoe

**Comment by remicollet** [comment]
From Joe:

> hmm, not sure about that ...
> it encourages a kind of incorrect way of thinking about channels ...
> you can execute ::closed and have it return false while another thread is concurrently blocked and waiting to close the channel, you have no way to tell what is really going on ...
> (because you can't hold the lock associated with the state of the channel, which the api maintains for you)

So will be delayed a bit until joe have more time to look on it

**Comment by krakjoe** [comment]
I think we have to say no here ... sorry it took so long :)

**Pull request closed without merging**
